# Generated by Django 4.0.6 on 2022-09-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profileImage',
        ),
    ]
