# Generated by Django 4.0.6 on 2022-09-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='follows',
            new_name='followsModel',
        ),
    ]
